####这个不需要
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: master-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: alicloud-disk-efficiency
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: work-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: alicloud-disk-efficiency