apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: psql-manual
provisioner: nasplugin.csi.alibabacloud.com
parameters:
  volumeAs: filesystem
reclaimPolicy: Retain
# allowVolumeExpansion: true
volumeBindingMode: Immediate