apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: postgres
    meta.helm.sh/release-namespace: postgres
  creationTimestamp: "2024-12-01T08:01:07Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/version: 4.5.5
    helm.sh/chart: postgresql-ha-15.0.2
    k8slens-edit-resource-version: v1
  name: postgres-postgresql-ha-pgpool
  namespace: postgres
  resourceVersion: "109377"
  uid: 480cc80b-8225-4983-a911-800cecb90284
spec:
  # allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.41.95
  clusterIPs:
  - 10.43.41.95
  # externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    # nodePort: 30569
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql-ha
  sessionAffinity: None
  type: ClusterIP
# status:
#   loadBalancer:
#     ingress:
#     - ip: 172.16.5.0
#       ipMode: VIP
#     - ip: 172.16.5.1
#       ipMode: VIP
