apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-0
  # name: data-datasaku-postgres-postgresql-ha-postgresql-0
  labels:
    app: postgres-app
spec:
  storageClassName: alicloud-disk-topology-alltype
  claimRef:
    name: data-postgres-postgresql-ha-postgresql-0
    namespace: postgres
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres/postgres0

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-1
  # name: data-datasaku-postgres-postgresql-ha-postgresql-1
  labels:
    app: postgres-app
spec:
  storageClassName: alicloud-disk-topology-alltype
  claimRef:
    name: data-postgres-postgresql-ha-postgresql-1
    namespace: postgres
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres/postgres1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-2
  # name: data-datasaku-postgres-postgresql-ha-postgresql-1
  labels:
    app: postgres-app
spec:
  storageClassName: alicloud-disk-topology-alltype
  claimRef:
    name: data-postgres-postgresql-ha-postgresql-2
    namespace: postgres
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres/postgres2