apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres-postgresql-ha-postgresql-0
  labels:
    app: postgres-app
spec:
  storageClassName: alicloud-disk-topology-alltype
  volumeName: postgres-volume-0
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres-postgresql-ha-postgresql-1
  labels:
    app: postgres-app
spec:
  storageClassName: alicloud-disk-topology-alltype
  volumeName: postgres-volume-1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-postgres-postgresql-ha-postgresql-2
  labels:
    app: postgres-app
spec:
  storageClassName: alicloud-disk-topology-alltype
  volumeName: postgres-volume-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi