apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk-topology-alltype
provisioner: diskplugin.csi.alibabacloud.com
parameters:
  type: cloud_essd_entry
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate