apiVersion: v2
name: demo
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql-ha
    version: "15.0.2"
    repository: oci://registry-1.docker.io/bitnamicharts
    

    
